# Generated by Django 5.1.3 on 2024-12-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='balls',
            field=models.IntegerField(default=0),
        ),
    ]
