# Generated by Django 5.1.3 on 2024-12-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_test_balls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='subject',
            new_name='question',
        ),
    ]
