# Generated by Django 5.1.3 on 2024-12-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_user_is_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
