# Generated by Django 5.1.3 on 2024-12-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_shop_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gifts',
            field=models.ManyToManyField(blank=True, related_name='gift', to='quiz.shop'),
        ),
    ]
